cmp-service:
    appSecrets:
        OPENAI_ORGANIZATION: 
        OPENAI_API_KEY: 
sops:
    kms:
        - arn: 
          created_at: 
          enc: 
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: ""
    mac: 
    pgp: []
    unencrypted_suffix: 
    version: 1.0.0